### ISSUE TITLE
Cannot extend type "Workhsop" because it does not exist in the existing schema.

### ISSUE THREAD

**Issue by grochadc** [marmelab/json-graphql-server#97] opened 2020-09-24 13:19 UTC
**What you were expecting:**

Starts a graphql server

**What happened instead:**

`a [GraphQLError]: Cannot extend type "Workhsop" because it does not exist in the existing schema.`

**Steps to reproduce:**

Create your own data instead of using the example data in the `README`

```javascript
module.exports = {
  workshops: [
    {
      id: 1,
      name: "Conversation",
      description:
        "El alumno se expresa oralmente utilizando las funciones comunicativas y vocabulario adquirido, mejorar la fluidez, y perder el temor a hablar.",
    },
    {
      id: 2,
      name: "TOEFL Preparation",
      description:
        "Ayuda a desarrollar habilidades para el examen de certificación, a partir del dominio ya adquirido del idioma. Duracion: 1 mes.",
    }
  options: [
    {
      id: 1,
      teacher: "alondra",
      time: "13:00 - 14:00",
      day: "lunes",
      workshop_id: 1,
    },
    {
      id: 2,
      teacher: "gonzalo",
      time: "14:00 - 15:00",
      day: "lunes",
      workshop_id: 1,
    },
    {
      id: 11,
      teacher: "carlos",
      time: "12:00 - 13:00",
      day: "lunes",
      workshop_id: 2,
    },
  ],
};
```

**Related code:**

```
npx json-graphql-server db.js
```

**Other information:**

**Environment**

* Last version that did not exhibit the issue (if applicable):
* Browser:

**Comment by colonaut** [comment] 2020-10-11 22:23
could it be you lack a closing array literal and a comma before "options:  [" ?
Guess it should be

 ```
exports = {
    workshops: [
        {
            id: 1,
            name: "Conversation",
            description:
              "El alumno se expresa oralmente utilizando las funciones comunicativas y vocabulario adquirido, mejorar la fluidez, y perder el temor a hablar.",
        },
        {
            id: 2,
            name: "TOEFL Preparation",
            description:
              "Ayuda a desarrollar habilidades para el examen de certificación, a partir del dominio ya adquirido del idioma. Duracion: 1 mes.",
        }
    **],**
    options: [
        {
            id: 1,
            teacher: "alondra",
            time: "13:00 - 14:00",
            day: "lunes",
            workshop_id: 1,
        },
        {
            id: 2,
            teacher: "gonzalo",
            time: "14:00 - 15:00",
            day: "lunes",
            workshop_id: 1,
        },
        {
            id: 11,
            teacher: "carlos",
            time: "12:00 - 13:00",
            day: "lunes",
            workshop_id: 2,
        },
    ],
};
```

WITH the correct object notation it works for me at least...

**Comment by ozanmuyes** [comment] 2021-03-26 18:20
Workhsop vs
Workshop
Could it be the cause?

**Closed** 2021-03-26 20:01 UTC
